version: '3' 

networks:
  app-network:
    driver: bridge  

services: 
  app: 
    build:
      context: ../
      dockerfile: .docker/app.Dockerfile
    image: app
    networks:
      - app-network

  nginx: 
    build:
      context: ../
      dockerfile: .docker/nginx.Dockerfile
    image: nginx
    ports: 
      - '80:80'
    depends_on: 
      - app
    networks:
      - app-network
    command: [
      "/bin/bash", 
      "-c",
      "sed -i 's|ENV(APP_PORT)|'$PORT'|g' /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    ]